[tool.poetry]
name = "chat-ui"
version = "0.1.0"
description = ""
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
readme = "README.md"
packages = [{ include = "chat_ui" }]

[tool.poetry.dependencies]

python = "^3.10"
fastapi = "^0.109.2"
pydantic = "^2.6.1"
uvicorn = "^0.23.2"
click = "^8.1.6"
fortune-python = "^1.1.1"
itsdangerous = "^2.1.2"
python-multipart = "^0.0.9"
pydantic-settings = "^2.1.0"
structlog = "^24.1.0"
loguru = "^0.7.2"
sqlalchemy = "^2.0.26"
websocket = "^0.2.1"
websockets = "^12.0"
aiohttp = "^3.9.3"
requests = "^2.31.0"
openai = "^1.12.0"
sqlmodel = "^0.0.14"
prometheus-fastapi-instrumentator = "^6.1.0"
cmarkgfm = "^2024.1.14"

[tool.poetry.group.dev.dependencies]
mypy = "^1.5.0"
black = "^24.2.0"
ruff = "^0.2.1"
pytest = "^8.0.0"
httpx = "^0.24.1"
mkdocs = { version = "^1.5.3", extras = ["python"] }
mkdocs-material = "^9.5.9"
markdown-mdantic = "^2.1.0"
types-requests = "^2.31.0.20240125"


[tool.poetry.group.llama.dependencies]
llama-cpp-python = {extras = ["server"], version = "^0.2.53"}

[tool.poetry.scripts]
chat-ui = "chat_ui.__main__:main"

[tool.ruff]
line-length = 120

[tool.mypy]
plugins = "pydantic.mypy"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "chat-ui"
description = ""
version = "0.1.0"
readme = "README.md"
authors = [{ name = "James Hodgkinson", email = "james@terminaloutcomes.com" }]
